-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2026-05-26 18:13:13 BRT
--   site:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE T_ECO_ACAO_SUSTENTAVEL 
    ( 
     id_acao           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_usuario        NUMBER  NOT NULL , 
     id_categoria      NUMBER  NOT NULL , 
     id_temporada      NUMBER  NOT NULL , 
     ds_descricao      VARCHAR2 (255)  NOT NULL , 
     qt_quantidade     NUMBER (10,2)  NOT NULL , 
     qt_pontos_gerados NUMBER (10,2)  NOT NULL , 
     dt_acao           DATE  NOT NULL , 
     st_acao           VARCHAR2 (10)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_ACAO_SUSTENTAVEL 
    ADD CONSTRAINT CK_ACAO_STATUS 
    CHECK (st_acao IN ('PENDENTE','VALIDADA','RECUSADA'))
;
ALTER TABLE T_ECO_ACAO_SUSTENTAVEL 
    ADD CONSTRAINT PK_T_ECO_ACAO PRIMARY KEY ( id_acao ) ;

CREATE TABLE T_ECO_CATEGORIA 
    ( 
     id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nm_categoria VARCHAR2 (80)  NOT NULL , 
     ds_categoria VARCHAR2 (255) , 
     vl_peso      NUMBER (5,2)  NOT NULL , 
     st_categoria VARCHAR2 (10)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_CATEGORIA 
    ADD CONSTRAINT CK_CATEGORIA_STATUS 
    CHECK (st_categoria IN ('ATIVA', 'INATIVA'))
;
ALTER TABLE T_ECO_CATEGORIA 
    ADD CONSTRAINT PK_T_ECO_CATEGORIA PRIMARY KEY ( id_categoria ) ;

CREATE TABLE T_ECO_CONQUISTA 
    ( 
     id_conquista NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nm_conquista VARCHAR2 (100)  NOT NULL , 
     ds_conquista VARCHAR2 (255) , 
     ds_criterio  VARCHAR2 (255) , 
     st_conquista VARCHAR2 (10)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_CONQUISTA 
    ADD CONSTRAINT CK_CONQUISTA_STATUS 
    CHECK (st_conquista IN ('ATIVA', 'INATIVA'))
;
ALTER TABLE T_ECO_CONQUISTA 
    ADD CONSTRAINT PK_T_ECO_CONQUISTA PRIMARY KEY ( id_conquista ) ;

CREATE TABLE T_ECO_EVIDENCIA 
    ( 
     id_evidencia      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_acao           NUMBER  NOT NULL , 
     ds_tipo_evidencia VARCHAR2 (30)  NOT NULL , 
     ds_url_arquivo    VARCHAR2 (255)  NOT NULL , 
     dt_envio          DATE  NOT NULL , 
     st_evidencia      VARCHAR2 (15)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_EVIDENCIA 
    ADD CONSTRAINT CK_EVIDENCIA_STATUS 
    CHECK (st_evidencia IN ('SUBMETIDA','APROVADA','RECUSADA'))
;
ALTER TABLE T_ECO_EVIDENCIA 
    ADD CONSTRAINT PK_T_ECO_EVIDENCIA PRIMARY KEY ( id_evidencia ) ;

CREATE TABLE T_ECO_IMPACTO 
    ( 
     id_impacto         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_usuario         NUMBER  NOT NULL , 
     id_temporada       NUMBER  NOT NULL , 
     qt_arvore_plantada NUMBER (10,2) DEFAULT 0 , 
     qt_composto_kg     NUMBER (10,2) DEFAULT 0 , 
     qt_polinizador     NUMBER (10,2) DEFAULT 0 , 
     qt_reciclado_kg    NUMBER (10,2) DEFAULT 0 , 
     qt_agua_litro      NUMBER (10,2) DEFAULT 0 , 
     qt_energia_kwh     NUMBER (10,2) DEFAULT 0 , 
     dt_atualizacao     DATE  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_IMPACTO 
    ADD CONSTRAINT PK_T_ECO_IMPACTO PRIMARY KEY ( id_impacto ) ;

ALTER TABLE T_ECO_IMPACTO 
    ADD CONSTRAINT UK_IMPACTO_USUARIO_TEMPORADA UNIQUE ( id_usuario , id_temporada ) ;

CREATE TABLE T_ECO_RANKING_USUARIO 
    ( 
     id_ranking_usuario   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_usuario           NUMBER  NOT NULL , 
     id_temporada         NUMBER  NOT NULL , 
     qt_pontos_acumulados NUMBER (10,2)  NOT NULL , 
     nr_posicao           NUMBER (5) , 
     dt_atualizacao       DATE  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_RANKING_USUARIO 
    ADD CONSTRAINT PK_T_ECO_RANKING_USUARIO PRIMARY KEY ( id_ranking_usuario ) ;

ALTER TABLE T_ECO_RANKING_USUARIO 
    ADD CONSTRAINT UK_RANKING_USUARIO_TEMPORADA UNIQUE ( id_usuario , id_temporada ) ;

CREATE TABLE T_ECO_TEMPORADA 
    ( 
     id_temporada    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nm_temporada    VARCHAR2 (100)  NOT NULL , 
     dt_inicio       DATE  NOT NULL , 
     dt_encerramento DATE , 
     qt_meta_pontos  NUMBER  NOT NULL , 
     st_temporada    VARCHAR2 (10)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_TEMPORADA 
    ADD CONSTRAINT CK_TEMPORADA_STATUS 
    CHECK (st_temporada IN ('ATIVA', 'ENCERRADA'))
;
ALTER TABLE T_ECO_TEMPORADA 
    ADD CONSTRAINT PK_T_ECO_TEMPORADA PRIMARY KEY ( id_temporada ) ;

CREATE TABLE T_ECO_USUARIO 
    ( 
     id_usuario    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nm_usuario    VARCHAR2 (100)  NOT NULL , 
     ds_email      VARCHAR2 (120)  NOT NULL , 
     ds_senha_hash VARCHAR2 (255)  NOT NULL , 
     dt_cadastro   DATE  NOT NULL , 
     st_usuario    VARCHAR2 (10)  NOT NULL , 
     fl_admin      CHAR (1)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_USUARIO 
    ADD CONSTRAINT CK_USUARIO_ADMIN 
    CHECK (fl_admin IN ('S', 'N'))
;


ALTER TABLE T_ECO_USUARIO 
    ADD CONSTRAINT CK_USUARIO_STATUS 
    CHECK (st_usuario IN ('ATIVO', 'INATIVO'))
;
ALTER TABLE T_ECO_USUARIO 
    ADD CONSTRAINT PK_T_ECO_USUARIO PRIMARY KEY ( id_usuario ) ;

ALTER TABLE T_ECO_USUARIO 
    ADD CONSTRAINT UK_USUARIO_EMAIL UNIQUE ( ds_email ) ;

CREATE TABLE T_ECO_USUARIO_CONQUISTA 
    ( 
     id_usuario_conquista NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_usuario           NUMBER  NOT NULL , 
     id_conquista         NUMBER  NOT NULL , 
     dt_desbloqueio       DATE  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_USUARIO_CONQUISTA 
    ADD CONSTRAINT PK_T_ECO_USUARIO_CONQUISTA PRIMARY KEY ( id_usuario_conquista ) ;

ALTER TABLE T_ECO_USUARIO_CONQUISTA 
    ADD CONSTRAINT UK_USUARIO_CONQUISTA UNIQUE ( id_usuario , id_conquista ) ;

CREATE TABLE T_ECO_VALIDACAO 
    ( 
     id_validacao         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_evidencia         NUMBER  NOT NULL , 
     id_usuario_validador NUMBER , 
     ds_tipo_validacao    VARCHAR2 (30)  NOT NULL , 
     st_resultado         VARCHAR2 (10)  NOT NULL , 
     vl_confiabilidade    NUMBER (5,2) , 
     dt_validacao         DATE  NOT NULL , 
     ds_observacao        VARCHAR2 (255) 
    ) 
    LOGGING 
;

ALTER TABLE T_ECO_VALIDACAO 
    ADD CONSTRAINT CK_VALIDACAO_RESULTADO 
    CHECK (st_resultado IN ('PENDENTE','APROVADA','RECUSADA'))
;
ALTER TABLE T_ECO_VALIDACAO 
    ADD CONSTRAINT PK_T_ECO_VALIDACAO PRIMARY KEY ( id_validacao ) ;

ALTER TABLE T_ECO_ACAO_SUSTENTAVEL 
    ADD CONSTRAINT FK_ACAO_CATEGORIA FOREIGN KEY 
    ( 
     id_categoria
    ) 
    REFERENCES T_ECO_CATEGORIA 
    ( 
     id_categoria
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_ACAO_SUSTENTAVEL 
    ADD CONSTRAINT FK_ACAO_TEMPORADA FOREIGN KEY 
    ( 
     id_temporada
    ) 
    REFERENCES T_ECO_TEMPORADA 
    ( 
     id_temporada
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_ACAO_SUSTENTAVEL 
    ADD CONSTRAINT FK_ACAO_USUARIO FOREIGN KEY 
    ( 
     id_usuario
    ) 
    REFERENCES T_ECO_USUARIO 
    ( 
     id_usuario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_EVIDENCIA 
    ADD CONSTRAINT FK_EVIDENCIA_ACAO FOREIGN KEY 
    ( 
     id_acao
    ) 
    REFERENCES T_ECO_ACAO_SUSTENTAVEL 
    ( 
     id_acao
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_IMPACTO 
    ADD CONSTRAINT FK_IMPACTO_TEMPORADA FOREIGN KEY 
    ( 
     id_temporada
    ) 
    REFERENCES T_ECO_TEMPORADA 
    ( 
     id_temporada
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_IMPACTO 
    ADD CONSTRAINT FK_IMPACTO_USUARIO FOREIGN KEY 
    ( 
     id_usuario
    ) 
    REFERENCES T_ECO_USUARIO 
    ( 
     id_usuario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_RANKING_USUARIO 
    ADD CONSTRAINT FK_RANKING_USUARIO_TEMPORADA FOREIGN KEY 
    ( 
     id_temporada
    ) 
    REFERENCES T_ECO_TEMPORADA 
    ( 
     id_temporada
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_RANKING_USUARIO 
    ADD CONSTRAINT FK_RANKING_USUARIO_USUARIO FOREIGN KEY 
    ( 
     id_usuario
    ) 
    REFERENCES T_ECO_USUARIO 
    ( 
     id_usuario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_USUARIO_CONQUISTA 
    ADD CONSTRAINT FK_USUARIO_CONQUISTA_CONQUISTA FOREIGN KEY 
    ( 
     id_conquista
    ) 
    REFERENCES T_ECO_CONQUISTA 
    ( 
     id_conquista
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_USUARIO_CONQUISTA 
    ADD CONSTRAINT FK_USUARIO_CONQUISTA_USUARIO FOREIGN KEY 
    ( 
     id_usuario
    ) 
    REFERENCES T_ECO_USUARIO 
    ( 
     id_usuario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_VALIDACAO 
    ADD CONSTRAINT FK_VALIDACAO_EVIDENCIA FOREIGN KEY 
    ( 
     id_evidencia
    ) 
    REFERENCES T_ECO_EVIDENCIA 
    ( 
     id_evidencia
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE T_ECO_VALIDACAO 
    ADD CONSTRAINT FK_VALIDACAO_USUARIO FOREIGN KEY 
    ( 
     id_usuario_validador
    ) 
    REFERENCES T_ECO_USUARIO 
    ( 
     id_usuario
    ) 
    NOT DEFERRABLE 
;



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             34
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
